sistema/config/routes.rb
Rails.application.routes.draw do
    
    resources :comments
    resources :articles
    post 'articles/:id/comments', to: 'comments#create', as: :comment_article
    get 'articles/comment/:id', to: 'comments#edit', as: :edit_comment_article
    patch 'articles/:id/like', to: 'articles#like', as: :like_article
    patch 'articles/:id/deslike', to: 'articles#deslike', as: :deslike_article
    
    
    # Rotas de UserController
    get 'users/crud', to: 'users#crud', as: :crud
    get 'users', to: 'users#index', as: :users
    get 'users/new', to: 'users#new', as: :user_new
    post 'users/new', to: 'users#create'
    get 'users/:id', to: 'users#show', as: :user
    get 'users/edit/:id', to: 'users#edit', as: :user_edit
    patch 'users/edit/:id', to: 'users#update'
    delete 'users/destroy/:id', to: 'users#destroy', as: :user_destroy
    
    #Rotas de SessionsController
    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create'
    delete 'logout',to: 'sessions#destroy', as: :logout
    
end

sistema/app/views/layouts/_messages.html.erb
<!-- Ira exibir os possiveis erros de operacoes do nosso sistema
Cores, :success => verde, :info => azul, :warning => amarelo, :danger => vermelho
-->
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
    <a class="close" data-dismiss="alert">&#215;</a>
  </div>
<% end %>

sistema/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> Sistema</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1> Especialização Back - IN Junior</h1>
      <%= link_to 'Usuários', users_path %>
      <%= link_to 'Novo Usuário', user_new_path %>
      <%= link_to 'Artigos', articles_path %>
      <%= link_to 'Comentários', comments_path %>
    </header>
    
    <% if logged_in?%>
      <p>Você está logado <%= current_user.name %> <%= link_to "Logout", logout_path, method: :delete %></p>
    <% end %>
    
    <%= render 'layouts/messages'%>
    
    <%= yield %>
  </body>
</html>